// 2026 Dog Derby — site content
// Edit this file to update sponsors, vendors, raffle items, or rescue partners.
// No build step needed — just save and refresh the page.

const SITE_DATA = {
  event: {
    name: "Dog Derby 2026",
    tagline: "A day of tails, treats, and community — presented by Stanley Steemer",
    date: "August 30, 2026 · 8:00 AM – 3:00 PM",
    location: "Monroeville Community Park West",
  },

  sponsorTiers: [
    {
      tier: "Presenting Sponsor",
      amount: null,
      sponsors: [{ name: "Stanley Steemer" }],
    },
    {
      tier: "Labrador Sponsor",
      amount: "$1,000",
      sponsors: [{ name: "West Shore Homes" }],
    },
    {
      tier: "Bulldog Sponsor",
      amount: "$500",
      sponsors: [
        { name: "Aaron Accounting" },
        { name: "S&T Bank" },
        { name: "Somma Pizza" },
        { name: "Compass Investments" },
        { name: "Greentree Auto Body" },
        { name: "Michaels Painting" },
        { name: "Zamp's Brew Thru" },
        { name: "Camp Bow Wow – Pittsburgh East" },
        { name: "Berkley Creek Pet Retreat" },
        { name: "Manso-Suprano Agency LLC" },
      ],
    },
    {
      tier: "Obstacle Sponsor",
      amount: "$100",
      sponsors: [{ name: "Double Take Detailing" }],
    },
  ],

  vendors: [
    { name: "Groove Coffee Co", category: "Food & Drink" },
    {
      name: "Los Gallitos",
      category: "Food & Drink",
      description: "Mexican food vendor offering tacos, quesadillas, nachos, and Mexican sodas.",
      website: "https://losgallitospittsburgh.com",
      instagram: "@losgallitospgh",
    },
    { name: "Joyful Rides Co", category: "Food & Drink" },
    { name: "The Lemon Lineup", category: "Food & Drink" },
    {
      name: "Shivers Shaved Ice & Dirty Soda",
      category: "Food & Drink",
      description: "Shaved ice in a variety of flavors, plus dirty sodas.",
      website: "https://shiverspgh.com",
      instagram: "@shiverspgh",
    },
    { name: "PGH Eatz", category: "Food & Drink" },
    { name: "Tipsy Gypsy Mobile Bar", category: "Food & Drink" },
    {
      name: "Millie's Homemade Ice Cream",
      category: "Food & Drink",
      description: "Homemade ice cream and dairy-free gelato with toppings.",
      website: "https://www.millieshomemade.com",
      instagram: "@millies",
    },
    { name: "Binko's Pepper Sauce", category: "Food & Drink" },
    { name: "Biondi Biscotti", category: "Food & Drink" },
    {
      name: "Acclamation Brewing",
      category: "Food & Drink",
      description: "Craft beer vendor.",
      website: "https://acclamationbrewing.com",
      instagram: "@acclamationbrewing",
    },
    { name: "Steel City Hot Dogs", category: "Food & Drink" },
    { name: "Couture Cupcakes", category: "Desserts" },

    { name: "Yinz and Yappers", category: "Pet Supplies" },
    { name: "Bentley's Doggie Bistro", category: "Pet Supplies" },
    { name: "Olivers Bow Ties", category: "Pet Accessories" },
    {
      name: "Griswold's Natural Pet Market",
      category: "Pet Supplies",
      description: "Healthy pet treats and food, featuring a special \"Dog Derby Crunch Shots\" item and free microchip scans.",
      website: "https://griswoldsnpm.com",
      instagram: "@griswoldsnaturalpetmarket",
    },
    {
      name: "Pawfect Match Outfitters",
      category: "Pet Accessories",
      description: "Handmade pet gear — collars, leashes, harnesses, bandanas, hoodies, coats, and matching human accessories.",
      website: "https://pawfectmatchoutfitters.com",
      instagram: "@pawfectmatchoutfitters",
    },
    { name: "Honey Stone Co.", category: "Pet Supplies" },
    { name: "Hollywood Feed", category: "Pet Supplies" },

    {
      name: "Animal Healing NOW",
      category: "Pet Health & Wellness",
      description: "Working with licensed veterinarians since 1999 to help support comfort, mobility, and overall well-being.",
      website: "https://www.animalhealingnow.com",
      instagram: "@animalhealingnow",
    },
    {
      name: "Doolittle's Pet Services",
      category: "Grooming",
      description: "Nail clipping, dremel services, and dog bath sign-ups on-site.",
      instagram: "@doolittlespetservices",
    },
    { name: "Pet Palace Resort", category: "Pet Boarding & Services" },
    { name: "Sugar Oats Farms", category: "Body Care" },
    { name: "Rebel Hound Pittsburgh / The Green Room", category: "Pet Services" },
    {
      name: "Silly Goose Jewelry",
      category: "Jewelry & Accessories",
      description: "Handcrafted hypoallergenic earrings with animal themes — $1 from every dog-themed pair sold is donated to rescue.",
      instagram: "@sillygoosejewelry",
    },
    {
      name: "Portrait Princess",
      category: "Pet Photography",
      description: "Pet photography services — photos, products, and digital files.",
      website: "https://www.portraitprincess.com",
      instagram: "@portrait.princess",
    },
    { name: "Pebble Petal Creations", category: "Jewelry & Accessories" },
    {
      name: "Wonder & Warmth Candle Co.",
      category: "Home Decor",
      description: "Hand-poured candles free from lead, petroleum, phthalates, and parabens. Debuting a new fall collection, with proceeds supporting a rescue's mental wellness program.",
      website: "https://www.wonderandwarmthcandles.com",
      instagram: "@wonderandwarmthcandles",
    },
    {
      name: "Ashcrafted Imagery",
      category: "Art & Home Decor",
      description: "Whimsical illustrative wall decor themed around plants and animals, including dog art prints, embroidery, and a special-edition t-shirt.",
      website: "https://www.ashcraftedartwork.com",
      instagram: "@ashcraftedimagery",
    },
    { name: "Sewickley Hounds Foundation", category: "Nonprofit Organization" },
    {
      name: "Invisible Fence of Pittsburgh",
      category: "Pet Safety",
      description: "Pet containment and safety solutions, with a PetSafe ball launcher giveaway.",
      website: "https://www.invisiblefence.com",
      instagram: "@invisiblefence",
    },
    {
      name: "Queen of Sparks",
      category: "Jewelry & Accessories",
      description: "Custom permanent jewelry and a beaded flower bar with interactive experiences.",
      instagram: "@queenofsparks",
    },
    { name: "Buggy's Bowties & Bandanas", category: "Pet Accessories" },
    {
      name: "Bianca Basilone – Realty One Group Landmark",
      category: "Real Estate",
      description: "Local real estate agent, offering free dog treat goody bags.",
      website: "https://biancabasilone.myrealtyonegroup.com",
      instagram: "@boughtwithbianca",
    },
    { name: "Happy Plant Botanicals", category: "Skincare" },
    {
      name: "Club Pilates Murrysville",
      category: "Fitness",
      description: "Free intro reformer pilates classes, plus a raffle for a 4-class pack.",
      website: "https://www.clubpilates.com/murrysville",
      instagram: "@clubpilatesmurrysville",
    },
    { name: "Inked and Linked", category: "Services" },
    { name: "Kate Buckley Photography", category: "Photography" },
    {
      name: "Integrity Psychological Associates",
      category: "Health & Wellness",
      description: "Psychology practice offering therapy and medication management, with pet-themed treats and information on-site.",
      website: "https://www.integritypsych.com",
      instagram: "@integritypsychologicalservices",
    },
    { name: "Smokey and Moo's Treats", category: "Pet Treats" },

    { name: "Steel City Mobile Mini Golf", category: "Activity" },
    { name: "PGH Party Creations, LLC", category: "Face Painting" },

    { name: "Pittsburgh Pet Fence", category: "Pet Services" },
    { name: "Fumo Cigar Bar", category: "Activity" },
    { name: "Puppy Paws Cafe", category: "Food & Drink" },
    { name: "Pup O Clock", category: "Pet Products" },
    { name: "Poppy's Crafty Corner", category: "Pet Accessories" },
    { name: "Full Count Threads", category: "Apparel" },
    { name: "The Howdy Chic Boutique", category: "Boutique & Apparel" },
    { name: "Charm Revival PGH", category: "Jewelry & Accessories" },
    { name: "Smoke and Venom Apothecary", category: "Apothecary & Fragrance" },
    { name: "Pawsitive Vibes PGH", category: "Event Planning" },
    { name: "hi Hemp Infused Crafts", category: "Home & Bath Goods" },
  ],

  raffleItems: [
    { donor: "Oakmont Candle Works", item: "Gift Basket" },
    { donor: "Keystone Cultures", item: "Gift Card" },
    { donor: "Toni Unleashed", item: "Basket of Yak Chews" },
    { donor: "Toni Unleashed", item: "Pup Lunch" },
    { donor: "Nylabone", item: "Chews and Treats" },
    { donor: "Bark Box", item: "Gift Certificate" },
    { donor: "Studio Glow PGH", item: "Gift Certificate (1-Year Expiration)" },
    { donor: "Pawfect Match Outfitters", item: "Gift Basket" },
    { donor: "Common Ground Botanicals", item: "Gift Basket" },
    { donor: "Dogs by Design", item: "Gift Basket" },
    { donor: "Zone 28", item: "Gift Certificate" },
    { donor: "5Iron Golf", item: "Gift Certificate" },
    { donor: "Smiling Goat Soap Company", item: "Gift Basket" },
    { donor: "Griswold's Natural Pet Market", item: "Gift Basket" },
    { donor: "Audubon Society of Western PA", item: "Gift Certificate" },
    { donor: "Better Sporting Dogs", item: "10-Foot Agility Tunnel" },
    { donor: "WilderDog", item: "Gift Basket" },
    { donor: "Fun Fore All", item: "Item TBD" },
    { donor: "Home Chef", item: "Gift Card" },
    { donor: "On Par Now", item: "Trackman Gift Certificate" },
    { donor: "Benebone", item: "Retail Product" },
    { donor: "Grandpa Joe's Candy Shop", item: "Gift Card" },
    { donor: "Venture Outdoors", item: "Gift Certificate" },
    { donor: "Happy Valley Hounds", item: "Gift Certificate" },
    { donor: "True Pal Co.", item: "Hats" },
    { donor: "Beyond Bedtime Books", item: "Gift Certificates (3 x $10)" },
    { donor: "The Farmers Burger", item: "Gift Card" },
    { donor: "Balance Brewing Co.", item: "Gift Card" },
    { donor: "Rebel Hound Pittsburgh", item: "Gift Basket" },
    { donor: "Doggy Deck Co.", item: "Gift Certificate" },
    { donor: "eCollar Technologies", item: "Gift Certificate" },
    { donor: "Allegro Bakery", item: "Gift Card" },
    { donor: "Cafe Conmigo", item: "Gift Card" },
    { donor: "Smushpets", item: "Basket of Items" },
    { donor: "Once Wild Pet", item: "Gift Basket" },
    { donor: "Hybrid Healing/Wellness Collective", item: "Item TBD" },
    { donor: "Stone Water Salon and Spa", item: "Item TBD" },
    { donor: "Treats and Boards", item: "Gift Certificate" },
    { donor: "Pets.to.Prints", item: "Gift Certificate" },
    { donor: "Kani Kouture", item: "Product Items" },
    { donor: "The Foggy Dog", item: "Gift Certificate" },
    { donor: "Vital Essentials", item: "Butcher Cut Protein Treats" },
    { donor: "Zippy Paws", item: "Basket of Items" },
    { donor: "Graza Olive Oil", item: "Basket of Oils" },
    { donor: "SALTT", item: "Variety Pack (3 x 30)" },
    { donor: "Kards Unlimited", item: "Gift Card" },
    { donor: "Yeti Pet", item: "Basket of Items" },
    { donor: "Forma Pasta", item: "Gift Card" },
    { donor: "Papa J's Twin Plaza", item: "Gift Card" },
    { donor: "Play.Pet.Brands", item: "Gift Card" },
    { donor: "Number 14 Boutique", item: "Gift Card" },
    { donor: "Full Throttle Adrenaline Park", item: "Gift Card" },
    { donor: "Kendra Scott", item: "Jewelry Piece" },
  ],

  rescuePartners: [
    "Great Pyrenees Club of Western PA Rescue",
    "One by One Rescue",
    "Orphans of the Storm",
    "Bark About It Rescue",
    "Team Memphis",
    "Furry Friends of St. Francis",
    "Save a Friend PR",
    "Warrior Canine Connection",
    "Furever Homes Doberman Rescue",
    "Monroeville Animal Shelter",
    "Butler County Humane Society",
    "Tiny Cause",
    "Death Row Dogs Sanctuary",
  ],
};
