// 2026 Dog Derby — site content
// Edit this file to update sponsors, vendors, raffle items, or rescue partners.
// No build step needed — just save and refresh the page.

const SITE_DATA = {
  event: {
    name: "Dog Derby 2026",
    tagline: "A day of tails, treats, and community",
    date: "August 30, 2026 · 8:00 AM – 3:00 PM",
    location: "Monroeville Community Park West",
  },

  presentingSponsor: {
    name: "Stanley Steemer",
    logo: "assets/sponsor-stanley-steemer.webp",
  },

  sponsors: [
    {
      name: "West Shore Homes",
      logo: "assets/sponsor-west-shore-home.png",
      website: "https://westshorehome.com",
      accentColor: "#0050a0",
    },
    {
      name: "Aaron Accounting",
      logo: "assets/sponsor-aaron-accounting.jpg",
      website: "https://aaronpc.net",
      accentColor: "#583828",
    },
    {
      name: "S&T Bank",
      logo: "assets/sponsor-st-bank.png",
      website: "https://www.stbank.com",
      accentColor: "#084890",
    },
    {
      name: "Somma Pizza",
      logo: "assets/sponsor-somma-pizza.png",
      website: "https://sommapizza.com",
      accentColor: "#f8d050",
    },
    {
      name: "Compass Investments",
      logo: "assets/sponsor-compass-investments.png",
      website: "https://compassinvestmentsllc.com",
      accentColor: "#183890",
    },
    {
      name: "Greentree Auto Body",
      logo: "assets/sponsor-greentree-auto-body.jpeg",
      website: "https://www.facebook.com/greentreeautobody/",
      accentColor: "#009038",
    },
    {
      name: "Michaels Painting",
      logo: "assets/sponsor-michaels-painting.png",
      website: "https://www.facebook.com/people/Michaels-Painting/100090018221852/",
      accentColor: "#006028",
    },
    {
      name: "Zamp's Brew Thru",
      logo: "assets/sponsor-zamps-brew-thru.png",
      website: "https://zampsbrewthru.com",
      accentColor: "#2800f8",
    },
    {
      name: "Camp Bow Wow – Pittsburgh East",
      logo: "assets/sponsor-camp-bow-wow.png",
      website: "https://www.campbowwow.com/pittsburgh-east/",
      accentColor: "#a01830",
    },
    {
      name: "Berkley Creek Pet Retreat",
      logo: "assets/sponsor-berkley-creek.png",
      website: "https://berkleycreekpetretreat.com",
      accentColor: "#c8a890",
    },
    {
      name: "Manso-Suprano Agency LLC",
      logo: "assets/sponsor-manso-suprano-icon.png",
      website: "https://mansosupranoagency.com",
      accentColor: "#d0a058",
      showNameCaption: true,
    },
    {
      name: "Double Take Detailing",
      website: "https://doubletakedetailingdelmont.com",
      accentColor: "#1b2a4a",
    },
    {
      name: "Nerf Dog",
      logo: "assets/sponsor-nerf-dog.png",
      website: "http://www.nerfpet.com",
      accentColor: "#f05820",
    },
    {
      name: "Penneco Outdoor Advertising",
      logo: "assets/sponsor-penneco.png",
      website: "https://pennecooutdoor.com",
      accentColor: "#005038",
    },
    {
      name: "Tyler Mountain Water",
      logo: "assets/sponsor-tyler-mountain-water.png",
      website: "https://www.tylermountainwater.com",
      accentColor: "#006030",
    },
    {
      name: "Tees n Tops",
      logo: "assets/sponsor-tees-n-tops.png",
      website: "https://www.tees-n-tops.com",
      accentColor: "#1b2a4a",
    },
  ],

  vendors: [
    { name: "Groove Coffee Co", category: "Food & Drink", logo: "assets/vendor-groove-coffee.png" },
    {
      name: "Los Gallitos",
      category: "Food & Drink",
      logo: "assets/vendor-los-gallitos.png",
      description: "Mexican food vendor offering tacos, quesadillas, nachos, and Mexican sodas.",
      website: "https://losgallitospittsburgh.com",
      instagram: "@losgallitospgh",
    },
    { name: "Joyful Rides Co", category: "Food & Drink", logo: "assets/vendor-joyful-rides.jpg" },
    { name: "The Lemon Lineup", category: "Food & Drink", logo: "assets/vendor-lemon-lineup.jpg" },
    {
      name: "Shivers Shaved Ice & Dirty Soda",
      category: "Food & Drink",
      logo: "assets/vendor-shivers.png",
      description: "Shaved ice in a variety of flavors, plus dirty sodas.",
      website: "https://shiverspgh.com",
      instagram: "@shiverspgh",
    },
    { name: "PGH Eatz", category: "Food & Drink", logo: "assets/vendor-pgh-eatz.webp" },
    { name: "Tipsy Gypsy Mobile Bar", category: "Food & Drink", logo: "assets/vendor-tipsy-gypsy.png" },
    {
      name: "Millie's Homemade Ice Cream",
      category: "Food & Drink",
      logo: "assets/vendor-millies.jpg",
      description: "Homemade ice cream and dairy-free gelato with toppings.",
      website: "https://www.millieshomemade.com",
      instagram: "@millies",
    },
    { name: "Binko's Pepper Sauce", category: "Food & Drink", logo: "assets/vendor-binkos.jpg" },
    { name: "Biondi Biscotti", category: "Food & Drink", logo: "assets/vendor-biondi-biscotti.webp" },
    {
      name: "Acclamation Brewing",
      category: "Food & Drink",
      logo: "assets/vendor-acclamation.jpg",
      description: "Craft beer vendor.",
      website: "https://acclamationbrewing.com",
      instagram: "@acclamationbrewing",
    },
    { name: "Steel City Hot Dogs", category: "Food & Drink", logo: "assets/vendor-steel-city-hot-dogs.jpg" },
    {
      name: "Couture Cupcakes",
      category: "Desserts",
      description: "Cookies, cake pops, cupcakes, and stickers.",
      website: "https://www.couturecupcakespgh.com",
      instagram: "@Couture_cupcakesPGH",
    },

    { name: "Yinz and Yappers", category: "Pet Supplies", logo: "assets/vendor-yinz-yappers.jpg" },
    { name: "Bentley's Doggie Bistro", category: "Pet Supplies", logo: "assets/vendor-bentleys.png" },
    { name: "Olivers Bow Ties", category: "Pet Accessories", logo: "assets/vendor-olivers-bow-ties.png" },
    {
      name: "Griswold's Natural Pet Market",
      category: "Pet Supplies",
      logo: "assets/vendor-griswolds.png",
      description: "Healthy pet treats and food, featuring a special \"Dog Derby Crunch Shots\" item and free microchip scans.",
      website: "https://griswoldsnpm.com",
      instagram: "@griswoldsnaturalpetmarket",
    },
    {
      name: "Pawfect Match Outfitters",
      category: "Pet Accessories",
      logo: "assets/vendor-pawfect-match.jpg",
      description: "Handmade pet gear — collars, leashes, harnesses, bandanas, hoodies, coats, and matching human accessories.",
      website: "https://pawfectmatchoutfitters.com",
      instagram: "@pawfectmatchoutfitters",
    },
    { name: "Honey Stone Co.", category: "Pet Supplies", logo: "assets/vendor-honeystone.webp" },
    {
      name: "Hollywood Feed",
      category: "Pet Supplies",
      logo: "assets/vendor-hollywood-feed.jpg",
      description: "Pet supply retailer featuring toys, healthy treats, and long-lasting chews, with frequent-feeder rewards and same-day delivery.",
      website: "https://www.hollywoodfeed.com",
      instagram: "@hwfeed",
    },

    {
      name: "Animal Healing NOW",
      category: "Pet Health & Wellness",
      logo: "assets/vendor-animal-healing.png",
      description: "Working with licensed veterinarians since 1999 to help support comfort, mobility, and overall well-being. Dr. Savko's new book, The Conscious Animal Companion, releases worldwide in September 2026.",
      website: "https://www.animalhealingnow.com",
      instagram: "@animalhealingnow",
    },
    {
      name: "Doolittle's Pet Services",
      category: "Grooming",
      logo: "assets/vendor-doolittles.jpg",
      description: "Nail clipping, dremel services, and dog bath sign-ups on-site.",
      instagram: "@doolittlespetservices",
    },
    { name: "Pet Palace Resort", category: "Pet Boarding & Services", logo: "assets/vendor-pet-palace.png" },
    { name: "Sugar Oats Farms", category: "Body Care", logo: "assets/vendor-sugar-oats.jpg" },
    {
      name: "Rebel Hound Pittsburgh / The Green Room",
      category: "Pet Services",
      logo: "assets/vendor-rebel-hound.jpg",
    },
    {
      name: "Silly Goose Jewelry",
      category: "Jewelry & Accessories",
      logo: "assets/vendor-silly-goose.png",
      description: "Handcrafted hypoallergenic earrings with animal themes — $1 from every dog-themed pair sold is donated to rescue.",
      instagram: "@sillygoosejewelry",
    },
    {
      name: "Portrait Princess",
      category: "Pet Photography",
      logo: "assets/vendor-portrait-princess.webp",
      description: "Pet photography services — photos, products, and digital files.",
      website: "https://www.portraitprincess.com",
      instagram: "@portrait.princess",
    },
    { name: "Pebble Petal Creations", category: "Jewelry & Accessories", logo: "assets/vendor-pebble-petal.jpg" },
    {
      name: "Wonder & Warmth Candle Co.",
      category: "Home Decor",
      logo: "assets/vendor-wonder-warmth.png",
      description: "Hand-poured candles free from lead, petroleum, phthalates, and parabens. Debuting a new fall collection, with proceeds supporting a rescue's mental wellness program.",
      website: "https://www.wonderandwarmthcandles.com",
      instagram: "@wonderandwarmthcandles",
    },
    {
      name: "Ashcrafted Imagery",
      category: "Art & Home Decor",
      logo: "assets/vendor-ashcrafted.png",
      description: "Whimsical illustrative wall decor themed around plants and animals, including dog art prints, embroidery, and a special-edition t-shirt.",
      website: "https://www.ashcraftedartwork.com",
      instagram: "@ashcraftedimagery",
    },
    {
      name: "Sewickley Hounds Foundation",
      category: "Nonprofit Organization",
      logo: "assets/vendor-sewickley-hounds.webp",
    },
    {
      name: "Invisible Fence of Pittsburgh",
      category: "Pet Safety",
      logo: "assets/vendor-invisible-fence.jpg",
      description: "Pet containment and safety solutions, with a PetSafe ball launcher giveaway.",
      website: "https://www.invisiblefence.com",
      instagram: "@invisiblefence",
    },
    {
      name: "Queen of Sparks",
      category: "Jewelry & Accessories",
      logo: "assets/vendor-queen-of-sparks.jpg",
      description: "Custom permanent jewelry and a beaded flower bar with interactive experiences.",
      instagram: "@queenofsparks",
    },
    {
      name: "Buggy's Bowties & Bandanas",
      category: "Pet Accessories",
      logo: "assets/vendor-buggys-bowties.png",
    },
    {
      name: "Bianca Basilone – Realty One Group Landmark",
      category: "Real Estate",
      logo: "assets/vendor-bianca-basilone.png",
      description: "Local real estate agent, offering free dog treat goody bags.",
      website: "https://biancabasilone.myrealtyonegroup.com",
      instagram: "@boughtwithbianca",
    },
    { name: "Happy Plant Botanicals", category: "Skincare", logo: "assets/vendor-happy-plant.jpg" },
    {
      name: "Club Pilates Murrysville",
      category: "Fitness",
      logo: "assets/vendor-club-pilates.jpg",
      description: "Free intro reformer pilates classes, plus a raffle for a 4-class pack.",
      website: "https://www.clubpilates.com/murrysville",
      instagram: "@clubpilatesmurrysville",
    },
    {
      name: "Inked and Linked",
      category: "Services",
      logo: "assets/vendor-inked-linked.webp",
      darkCard: true,
    },
    { name: "Kate Buckley Photography", category: "Photography", logo: "assets/vendor-kate-buckley.png" },
    {
      name: "Integrity Psychological Services",
      category: "Health & Wellness",
      logo: "assets/vendor-integrity-psych.png",
      description: "Psychology practice offering therapy and medication management, with pet-themed treats and information on-site.",
      website: "https://www.integritypsych.com",
      instagram: "@integritypsychologicalservices",
    },
    { name: "Smokey and Moo's Treats", category: "Pet Treats", logo: "assets/vendor-smokey-moos.png" },
    { name: "Dogtopia", category: "Pet Boarding & Services", logo: "assets/vendor-dogtopia.jpeg" },
    { name: "Warrior Canine Connection", category: "Nonprofit Organization", logo: "assets/vendor-warrior-canine.webp" },

    { name: "Steel City Mobile Mini Golf", category: "Activity", logo: "assets/vendor-steel-city-mini-golf.png" },
    { name: "PGH Party Creations, LLC", category: "Face Painting", logo: "assets/vendor-pgh-party-creations.png" },

    { name: "Pittsburgh Pet Fence", category: "Pet Services" },
    { name: "Fumo Cigar Bar", category: "Activity" },
    { name: "Puppy Paws Cafe", category: "Food & Drink" },
    { name: "Pup O Clock", category: "Pet Products" },
    { name: "Poppy's Crafty Corner", category: "Pet Accessories" },
    { name: "Full Count Threads", category: "Apparel" },
    { name: "The Howdy Chic Boutique", category: "Boutique & Apparel" },
    { name: "Charm Revival PGH", category: "Jewelry & Accessories" },
    { name: "Smoke and Venom Apothecary", category: "Apothecary & Fragrance" },
    { name: "Pawsitive Vibes PGH", category: "Event Planning" },
    { name: "hi Hemp Infused Crafts", category: "Home & Bath Goods" },
  ],

  raffleItems: [
    { donor: "Oakmont Candle Works", item: "Gift Basket" },
    { donor: "Keystone Cultures", item: "Gift Card" },
    { donor: "Toni Unleashed", item: "Basket of Yak Chews" },
    { donor: "Toni Unleashed", item: "Pup Lunch" },
    { donor: "Nylabone", item: "Chews and Treats" },
    { donor: "Bark Box", item: "Gift Certificate" },
    { donor: "Studio Glow PGH", item: "Gift Certificate (1-Year Expiration)" },
    { donor: "Pawfect Match Outfitters", item: "Gift Basket" },
    { donor: "Common Ground Botanicals", item: "Gift Basket" },
    { donor: "Dogs by Design", item: "Gift Basket" },
    { donor: "Zone 28", item: "Gift Certificate" },
    { donor: "5Iron Golf", item: "Gift Certificate" },
    { donor: "Smiling Goat Soap Company", item: "Gift Basket" },
    { donor: "Griswold's Natural Pet Market", item: "Gift Basket" },
    { donor: "Audubon Society of Western PA", item: "Gift Certificate" },
    { donor: "Better Sporting Dogs", item: "10-Foot Agility Tunnel" },
    { donor: "WilderDog", item: "Gift Basket" },
    { donor: "Fun Fore All", item: "Item TBD" },
    { donor: "Home Chef", item: "Gift Card" },
    { donor: "On Par Now", item: "Trackman Gift Certificate" },
    { donor: "Benebone", item: "Retail Product" },
    { donor: "Grandpa Joe's Candy Shop", item: "Gift Card" },
    { donor: "Venture Outdoors", item: "Gift Certificate" },
    { donor: "Happy Valley Hounds", item: "Gift Certificate" },
    { donor: "True Pal Co.", item: "Hats" },
    { donor: "Beyond Bedtime Books", item: "Gift Certificates (3 x $10)" },
    { donor: "The Farmers Burger", item: "Gift Card" },
    { donor: "Balance Brewing Co.", item: "Gift Card" },
    { donor: "Rebel Hound Pittsburgh", item: "Gift Basket" },
    { donor: "Doggy Deck Co.", item: "Gift Certificate" },
    { donor: "eCollar Technologies", item: "Gift Certificate" },
    { donor: "Allegro Bakery", item: "Gift Card" },
    { donor: "Cafe Conmigo", item: "Gift Card" },
    { donor: "Smushpets", item: "Basket of Items" },
    { donor: "Once Wild Pet", item: "Gift Basket" },
    { donor: "Hybrid Healing/Wellness Collective", item: "Item TBD" },
    { donor: "Stone Water Salon and Spa", item: "Item TBD" },
    { donor: "Treats and Boards", item: "Gift Certificate" },
    { donor: "Pets.to.Prints", item: "Gift Certificate" },
    { donor: "Kani Kouture", item: "Product Items" },
    { donor: "The Foggy Dog", item: "Gift Certificate" },
    { donor: "Vital Essentials", item: "Butcher Cut Protein Treats" },
    { donor: "Zippy Paws", item: "Basket of Items" },
    { donor: "Graza Olive Oil", item: "Basket of Oils" },
    { donor: "SALTT", item: "Variety Pack (3 x 30)" },
    { donor: "Kards Unlimited", item: "Gift Card" },
    { donor: "Yeti Pet", item: "Basket of Items" },
    { donor: "Forma Pasta", item: "Gift Card" },
    { donor: "Papa J's Twin Plaza", item: "Gift Card" },
    { donor: "Play.Pet.Brands", item: "Gift Card" },
    { donor: "Number 14 Boutique", item: "Gift Card" },
    { donor: "Full Throttle Adrenaline Park", item: "Gift Card" },
    { donor: "Kendra Scott", item: "Jewelry Piece" },
  ],

  rescuePartners: [
    "Great Pyrenees Club of Western PA Rescue",
    "One by One Rescue",
    "Orphans of the Storm",
    "Bark About It Rescue",
    "Team Memphis",
    "Furry Friends of St. Francis",
    "Save a Friend PR",
    "Furever Homes Doberman Rescue",
    "Monroeville Animal Shelter",
    "Butler County Humane Society",
    "Tiny Cause",
    "Death Row Dogs Sanctuary",
  ],
};
